project_id = "brtopjwrnghynluxyxsp"

[functions.process-scan]
verify_jwt = false

[functions.payment-webhook]
verify_jwt = false

[functions.initiate-payment]
verify_jwt = true

[functions.verify-payment]
verify_jwt = true
